spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/isob
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      schema-locations: classpath:schema.sql
